[[constraint]]
  branch = "release-1.15"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.15"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.0"
